name: Wulf
description: Sustainable solutions, one tap away.
full_description: '
<b>v1.0.0 (May 15, 2024)</b><br>
<br>- Initial release
<br>
'
android: https://play.google.com/store/apps/details?id=ee.wulf.android&utm_source=landing
iOS: false
web: false
screenshots:
  - 01-screenshot.png
  - 02-screenshot.png
  - 03-screenshot.png
  - 04-screenshot.png
producthunt: false
#companies:
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
